export const buttonsDefinitions = [
  { label: "AC", type: "btn" },
  { label: "delete", type: "btn" },
  { label: "%", type: "sign" },
  { label: "/", type: "sign" },
  { label: "7", type: "number" },
  { label: "8", type: "number" },
  { label: "9", type: "number" },
  { label: "x", type: "sign" },
  { label: "4", type: "number" },
  { label: "5", type: "number" },
  { label: "6", type: "number" },
  { label: "-", type: "sign" },
  { label: "1", type: "number" },
  { label: "2", type: "number" },
  { label: "3", type: "number" },
  { label: "+", type: "sign" },
  { label: "CC", type: "btn" },
  { label: "0", type: "number" },
  { label: ",", type: "sign" },
  { label: "=", type: "sign" },
];
